name: Deploy Product Service to Render

on:
  push:
    branches:
      - main
    paths:
      - 'product-service/**'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./product-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-service:latest

  deploy-to-render:
    needs: docker-build-push
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "accept: application/json" \
            -H "authorization: Bearer ${{ secrets.RENDER_API_KEY }}"


